all_cg_out_dir: ../../diff_pete/roadmap/
jobs_dir: ../jobs
training_data_folder: ../../diff_pete/roadmap/training_data
all_ct_segment_folder: ../../diff_pete/roadmap/all_ct_segments
chromhmm_state_num: 18
gene_region_fn: /u/project/ernst/havu73/diff_pete/roadmap/trial_gene_region_list  
state18_annot_fn: /u/project/ernst/havu73/data/roadmap_epigenome/18_core_K27ac_model_downloaded/state_annotation.txt
num_score_bins_roc: 100
all_ct_chrom_pos_folder: ../../data/roadmap_epigenome/18_core_K27ac_model_downloaded/posterior/